set shell := ["fish", "-c"]

tn NAME:
    tmux new -s {{ NAME }}

tnew NAME:
    tmux new -s {{ NAME }} -c (find ~ -type d | fzf)

tlist:
    tmux list-sessions

ta:
    tmux a

cds:
    cd (find ~ -type d | fzf)

edit:
    vim ~/justfile

[no-cd]
@ginit NAME:
    mkdir {{ NAME }}
    cd {{ NAME }}; go mod init {{ NAME }}
    cp ~/justdir/main.go {{ NAME }}
    cd {{ NAME }}; go fmt

[no-cd]
@cinit NAME:
    mkdir {{ NAME }}
    cp ~/justdir/main.c {{ NAME }}
    cp ~/justdir/justfile_c {{ NAME }}/justfile
