set shell := ["fish", "-c"]

tn NAME:
    tmux new -s {{ NAME }}

tnew NAME:
    tmux new -s {{ NAME }} -c (find ~ -type d | fzf)

tlist:
    tmux list-sessions

ta:
    tmux a

cds:
    cd (find ~ -type d | fzf)

edit:
    vim ~/justfile

[no-cd]
@gnew NAME:
    mkdir {{ NAME }}
    cd {{ NAME }}; go mod init {{ NAME }}
    cp ~/justdir/go/main.go {{ NAME }}
    cd {{ NAME }}; go fmt

[no-cd]
@cnew NAME:
    mkdir {{ NAME }}
    cp ~/justdir/c/main.c {{ NAME }}
    cp ~/justdir/c/justfile {{ NAME }}
    cp ~/justdir/c/clang-format {{ NAME }}/.clang-format

